# -*- coding: utf-8 -*-
"""main_Streamlit_resume.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-FSCco-rlDXAjrytCgjc6ldyuc-CimIM

1. main.py → Streamlit Frontend

Handles:
File uploads (JD + Resumes)

Calling backend logic

Displaying results
"""
# main.py
import os
os.environ["TRANSFORMERS_CACHE"] = "/tmp"
os.environ["HF_HOME"] = "/tmp"

import streamlit as st
from model import evaluate_hybrid_scores_from_text
import PyPDF2
import docx2txt

st.set_page_config(page_title="Resume Shortlisting AI", layout="wide")
st.title("🤖 Resume Shortlisting using BERT, SpaCy & TF-IDF")


def extract_text_from_file(file):
    if file.name.endswith(".pdf"):
        reader = PyPDF2.PdfReader(file)
        text = ""
        for page in reader.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text
        return text
    elif file.name.endswith(".docx"):
        return docx2txt.process(file)
    else:
        return ""


# Upload Job Description
st.header("📄 Upload Job Description")
jd_file = st.file_uploader("Upload JD (PDF or DOCX)", type=["pdf", "docx"])

# Upload Resumes
st.header("📂 Upload Resumes")
resume_files = st.file_uploader("Upload Resumes (PDFs or DOCX)", type=["pdf", "docx"], accept_multiple_files=True)

if st.button("🔍 Shortlist Candidates"):
    if not jd_file or not resume_files:
        st.warning("Please upload both JD and at least one resume.")
    else:
        # Extract JD text
        jd_text = extract_text_from_file(jd_file)

        # Extract text from resumes
        resume_dict = {res.name: extract_text_from_file(res) for res in resume_files}

        # Evaluate
        results = evaluate_hybrid_scores_from_text(jd_text, resume_dict)

        # Display
        st.success("✅ Shortlisting complete!")
        st.subheader("🏆 Top Candidates")

        for name, score in list(results.items())[:5]:
            st.markdown(f"**📌 {name}** — Score: `{score}`")

# !pip install docx2txt

