# -*- coding: utf-8 -*-
"""utils_resume.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/133vyoLUwl_Oq8ikwi4055ABhz8J8_h2B
"""

# utils.py

import PyPDF2
import io

def extract_text_from_uploaded_pdf(uploaded_file):
    text = ""
    reader = PyPDF2.PdfReader(uploaded_file)
    for page in reader.pages:
        content = page.extract_text()
        if content:
            text += content
    return text